name: Record Stream and Push

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"   # tiap hari jam 08:00 UTC (~16:00 WITA)

jobs:
  record_0:
    runs-on: ubuntu-latest

    steps:
      - name: Install Git LFS
        run: |
          sudo apt update
          sudo apt install -y git-lfs
          git lfs install

      - name: Clone repo
        env:
          MY_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          git clone https://github.com/Sparkplugx1904/VOT-Denpasar/
          cd VOT-Denpasar
          git lfs pull   # pastikan file ffmpeg besar ikut terdownload

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cd VOT-Denpasar
          pip install -r requirements.txt

      - name: Verify FFmpeg
        run: |
          cd VOT-Denpasar
          chmod +x ./ffmpeg 
          ./ffmpeg -version

      - name: Run recorder
        env:
          MY_ACC: ${{ secrets.MY_ACC }}
          MY_PASS: ${{ secrets.MY_PASS }}
        run: |
          cd VOT-Denpasar
          python record.py -0
