name: Record Radio Stream

on:
  schedule:
    # 17:00 WITA = 09:00 UTC
    - cron: "0 9 * * *"

jobs:
  record:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Record stream
        run: |
          mkdir -p recordings
          now=$(date +"%Y-%m-%d_%H-%M")
          # rekam 1 jam 30 menit (5400 detik), dengan bitrate kecil biar <100MB
          ffmpeg -y -i "https://i.klikhost.com:8502/stream" -t 5400 -b:a 64k "recordings/radio_$now.mp3"

      - name: Commit & push recording
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add recordings/
          git commit -m "Add recording at $(date -u)"
          git push
