name: Record Stream and Push

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"   # tiap hari jam 08:00 UTC (~16:00 WITA)

jobs:
  record_0:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Make ffmpeg executable
        run: chmod +x ./ffmpeg
      
      - name: Check ffmpeg version
        run: ./ffmpeg -version

      - name: Verify FFmpeg
        run: /home/runner/work/VOT-Denpasar/VOT-Denpasar/ffmpeg -version

      - name: Run recorder
        env:
          MY_ACC: ${{ secrets.MY_ACC }}
          MY_PASS: ${{ secrets.MY_PASS }}
        run: python record.py -0
