name: Record Radio Stream

on:
  schedule:
    - cron: "0 9 * * *"   # jalan jam 09:00 UTC = 17:00 WITA
  workflow_dispatch:

jobs:
  record:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Record raw stream
        run: |
          mkdir -p recordings
          now=$(date +"%Y-%m-%d_%H-%M")
          # ambil stream selama 5400 detik (1,5 jam)
          timeout 5400 curl -L "https://i.klikhost.com:8502/stream" -o "recordings/VOT-Denpasar_$now.mp3"

      - name: Commit & push recording
        run: |
          git config --global user.email "madyapadma_trisma@yahoo.com"
          git config --global user.name "GitHub Actions"
          git add recordings/
          git commit -m "Add raw recording at $(date -u)" || echo "No changes to commit"
          git push
