name: Record Stream and Push

on:
  workflow_dispatch:
  schedule:
    - cron: "50 8 * * *"

jobs:
  record:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run recorder
        env:
          MY_ACC: ${{ secrets.MY_ACC }}
          MY_PASS: ${{ secrets.MY_PASS }}
        run: |
          python recorder.py


      # - name: Commit & push recording
      #   env:
      #     MY_TOKEN: ${{ secrets.MY_TOKEN }}
      #   run: |
      #     git config --global user.email "madyapadma_trisma@yahoo.com"
      #     git config --global user.name "GitHub Actions"

      #     git add recordings/
      #     git commit -m "Add raw recording at $(date -u)" || echo "No changes to commit"

      #     git remote set-url origin https://x-access-token:${MY_TOKEN}@github.com/Sparkplugx1904/VOT-Denpasar.git
      #     git config --local --unset-all http.https://github.com/.extraheader || true
          
      #     git push origin main || echo "[ERROR] Push gagal"
