name: Record Stream and Push

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"   # tiap hari jam 08:00 UTC (~16:00 WITA)

jobs:
  record:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install FFmpeg and dependencies from local .deb
        run: |
          sudo dpkg -i bin/*.deb || sudo apt-get -f install -y

      - name: Verify FFmpeg
        run: ffmpeg -version

      - name: Run recorder
        env:
          MY_ACC: ${{ secrets.MY_ACC }}
          MY_PASS: ${{ secrets.MY_PASS }}
        run: python record.py

  record2: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install FFmpeg and dependencies from local .deb
        run: |
          sudo dpkg -i bin/*.deb || sudo apt-get -f install -y

      - name: Verify FFmpeg
        run: ffmpeg -version
        
  record3: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install FFmpeg and dependencies from local .deb
        run: |
          sudo dpkg -i bin/*.deb || sudo apt-get -f install -y

      - name: Verify FFmpeg
        run: ffmpeg -version

      - name: Run recorder
        env:
          MY_ACC: ${{ secrets.MY_ACC }}
          MY_PASS: ${{ secrets.MY_PASS }}
        run: python record.py
