name: Record Stream and Push

on:
  workflow_dispatch:   # bisa dijalankan manual
  schedule:
    - cron: "50 8 * * *"   # contoh: trigger tiap hari jam 16:50 UTC (~17:00 WITA)

jobs:
  record:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          mkdir -p recordings
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install -r requirements.txt

      - name: Run recording script
        run: |
          python record.py

      - name: Commit & push recording (debug super)
        env:
          MY_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          set -x  # debug: echo semua perintah yang jalan
      
          git config --global user.email "madyapadma_trisma@yahoo.com"
          git config --global user.name "GitHub Actions"
      
          # cek remote awal
          echo "[DEBUG] Remote sebelum diubah:"
          git remote -v
      
          # cek isi env token (sebagian aja biar ga bocor)
          echo "[DEBUG] Panjang token: ${#MY_TOKEN}"
          echo "[DEBUG] Awal token: ${MY_TOKEN:0:4}..."
      
          git add recordings/
          git commit -m "Add raw recording at $(date -u)" || echo "No changes to commit"
      
          # set remote pakai token
          echo "[DEBUG] Set remote dengan token..."
          git remote set-url origin https://Sparkplugx1904:${MY_TOKEN}@github.com/Sparkplugx1904/VOT-Denpasar.git
      
          # cek remote lagi setelah diubah
          echo "[DEBUG] Remote setelah diubah:"
          git remote -v
      
          # coba tes akses (tanpa push dulu)
          echo "[DEBUG] Coba git ls-remote..."
          git ls-remote origin || echo "[ERROR] ls-remote gagal"
      
          # baru push
          echo "[DEBUG] Push ke main..."
          git push origin main || echo "[ERROR] Push gagal"
