name: Record Stream and Push

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"   # tiap hari jam 08:00 UTC (~16:00 WITA)

jobs:
  record:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install FFmpeg via apt
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Verify FFmpeg
        run: ffmpeg -version

      - name: Run recorder
        env:
          MY_ACC: ${{ secrets.MY_ACC }}
          MY_PASS: ${{ secrets.MY_PASS }}
        run: python record.py

      - name: Commit & Push JSON log
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add recording.json
          git commit -m "Update log at $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git pull --rebase origin main || true
          git push origin HEAD:main || git push -f origin main
