name: Record Radio Stream

on:
  schedule:
    - cron: "0 9 * * *"   # jalan jam 09:00 UTC = 17:00 WITA
  workflow_dispatch:

jobs:
  record:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Wait until stream is available
        run: |
          url="https://i.klikhost.com:8502/stream"
          retries=60   # maksimal 10 menit (60 x 10 detik)
          count=0
          while [ $count -lt $retries ]; do
            status=$(curl -s -o /dev/null -w "%{http_code}" "$url")
            if [ "$status" = "200" ]; then
              echo "Stream is online (HTTP 200), starting recording..."
              break
            else
              echo "Stream not ready (HTTP $status), retrying in 10s..."
              sleep 10
              count=$((count+1))
            fi
          done
          if [ $count -eq $retries ]; then
            echo "Stream never became ready after $((retries*10))s, exiting."
            exit 1
          fi

      - name: Record raw stream
        run: |
          mkdir -p recordings
          now=$(date +"%Y-%m-%d_%H-%M")
          ffmpeg -i "https://i.klikhost.com:8502/stream" -c copy -t 5400 "recordings/VOT-Denpasar_$now.mp3"

      - name: Commit & push recording
        run: |
          git config --global user.email "madyapadma_trisma@yahoo.com"
          git config --global user.name "GitHub Actions"
          git add recordings/
          git commit -m "Add raw recording at $(date -u)" || echo "No changes to commit"
          git push
